days:
  Monday:
    AM:
      pickup: "Centennial Hotel - S"
      dropoff: "Wellcome Genome Campus"
    PM:
      pickup: "Wellcome Genome Campus"
      dropoff: "Brooklands Av - N (RQ)"
  Tuesday:
    AM:
      pickup: "Centennial Hotel - S"
      dropoff: "Wellcome Genome Campus"
    PM:
      pickup: "Wellcome Genome Campus"
      dropoff: "Brooklands Av - N (RQ)"
  Wednesday:
    AM:
      pickup: "Centennial Hotel - S"
      dropoff: "Wellcome Genome Campus"
    PM:
      pickup: "Wellcome Genome Campus"
      dropoff: "Brooklands Av - N (RQ)"
  Thursday:
    AM:
      pickup: "Centennial Hotel - S"
      dropoff: "Wellcome Genome Campus"
    PM:
      pickup: "Wellcome Genome Campus"
      dropoff: "Brooklands Av - N (RQ)"
  Friday:
    AM:
      pickup: "Centennial Hotel - S"
      dropoff: "Wellcome Genome Campus"
    PM:
      pickup: "Wellcome Genome Campus"
      dropoff: "Brooklands Av - N (RQ)"
