days:
  Monday:
    AM:
      pickup: "Centennial Hotel"
      dropoff: "Campus"
    PM:
      pickup: "Campus"
      dropoff: "Brooklands Av"
  Tuesday:
    AM:
      pickup: "Centennial Hotel"
      dropoff: "Campus"
    PM:
      pickup: "Campus"
      dropoff: "Brooklands Av"
  Wednesday:
    AM:
      pickup: "Centennial Hotel"
      dropoff: "Campus"
    PM:
      pickup: "Campus"
      dropoff: "Brooklands Av"
  Thursday:
    AM:
      pickup: "Centennial Hotel"
      dropoff: "Campus"
    PM:
      pickup: "Campus"
      dropoff: "Brooklands Av"
  Friday:
    AM:
      pickup: "Centennial Hotel"
      dropoff: "Campus"
    PM:
      pickup: "Campus"
      dropoff: "Brooklands Av"
